// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CRequestFight.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CRequestFight.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* CRequestFight_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CRequestFight_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CRequestFight_2eproto() {
  protobuf_AddDesc_CRequestFight_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CRequestFight.proto");
  GOOGLE_CHECK(file != NULL);
  CRequestFight_descriptor_ = file->message_type(0);
  static const int CRequestFight_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CRequestFight, fighthtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CRequestFight, fighthid_),
  };
  CRequestFight_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CRequestFight_descriptor_,
      CRequestFight::default_instance_,
      CRequestFight_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CRequestFight, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CRequestFight, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CRequestFight));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CRequestFight_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CRequestFight_descriptor_, &CRequestFight::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CRequestFight_2eproto() {
  delete CRequestFight::default_instance_;
  delete CRequestFight_reflection_;
}

void protobuf_AddDesc_CRequestFight_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023CRequestFight.proto\"5\n\rCRequestFight\022\022"
    "\n\nfighthType\030\001 \002(\005\022\020\n\010fighthId\030\002 \002(\005B4\n\""
    "com.thanple.gs.common.nio.protocolB\016_CRe"
    "questFight", 130);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CRequestFight.proto", &protobuf_RegisterTypes);
  CRequestFight::default_instance_ = new CRequestFight();
  CRequestFight::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CRequestFight_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CRequestFight_2eproto {
  StaticDescriptorInitializer_CRequestFight_2eproto() {
    protobuf_AddDesc_CRequestFight_2eproto();
  }
} static_descriptor_initializer_CRequestFight_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CRequestFight::kFighthTypeFieldNumber;
const int CRequestFight::kFighthIdFieldNumber;
#endif  // !_MSC_VER

CRequestFight::CRequestFight()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CRequestFight)
}

void CRequestFight::InitAsDefaultInstance() {
}

CRequestFight::CRequestFight(const CRequestFight& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CRequestFight)
}

void CRequestFight::SharedCtor() {
  _cached_size_ = 0;
  fighthtype_ = 0;
  fighthid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CRequestFight::~CRequestFight() {
  // @@protoc_insertion_point(destructor:CRequestFight)
  SharedDtor();
}

void CRequestFight::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CRequestFight::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CRequestFight::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CRequestFight_descriptor_;
}

const CRequestFight& CRequestFight::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CRequestFight_2eproto();
  return *default_instance_;
}

CRequestFight* CRequestFight::default_instance_ = NULL;

CRequestFight* CRequestFight::New() const {
  return new CRequestFight;
}

void CRequestFight::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<CRequestFight*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(fighthtype_, fighthid_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CRequestFight::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CRequestFight)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 fighthType = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fighthtype_)));
          set_has_fighthtype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_fighthId;
        break;
      }

      // required int32 fighthId = 2;
      case 2: {
        if (tag == 16) {
         parse_fighthId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fighthid_)));
          set_has_fighthid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CRequestFight)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CRequestFight)
  return false;
#undef DO_
}

void CRequestFight::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CRequestFight)
  // required int32 fighthType = 1;
  if (has_fighthtype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->fighthtype(), output);
  }

  // required int32 fighthId = 2;
  if (has_fighthid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->fighthid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CRequestFight)
}

::google::protobuf::uint8* CRequestFight::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CRequestFight)
  // required int32 fighthType = 1;
  if (has_fighthtype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->fighthtype(), target);
  }

  // required int32 fighthId = 2;
  if (has_fighthid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->fighthid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CRequestFight)
  return target;
}

int CRequestFight::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 fighthType = 1;
    if (has_fighthtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->fighthtype());
    }

    // required int32 fighthId = 2;
    if (has_fighthid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->fighthid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CRequestFight::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CRequestFight* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CRequestFight*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CRequestFight::MergeFrom(const CRequestFight& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_fighthtype()) {
      set_fighthtype(from.fighthtype());
    }
    if (from.has_fighthid()) {
      set_fighthid(from.fighthid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CRequestFight::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CRequestFight::CopyFrom(const CRequestFight& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CRequestFight::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void CRequestFight::Swap(CRequestFight* other) {
  if (other != this) {
    std::swap(fighthtype_, other->fighthtype_);
    std::swap(fighthid_, other->fighthid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CRequestFight::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CRequestFight_descriptor_;
  metadata.reflection = CRequestFight_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
