// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SFightMonsterInfo.proto

#ifndef PROTOBUF_SFightMonsterInfo_2eproto__INCLUDED
#define PROTOBUF_SFightMonsterInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_SFightMonsterInfo_2eproto();
void protobuf_AssignDesc_SFightMonsterInfo_2eproto();
void protobuf_ShutdownFile_SFightMonsterInfo_2eproto();

class SFightMonsterInfo;

// ===================================================================

class SFightMonsterInfo : public ::google::protobuf::Message {
 public:
  SFightMonsterInfo();
  virtual ~SFightMonsterInfo();

  SFightMonsterInfo(const SFightMonsterInfo& from);

  inline SFightMonsterInfo& operator=(const SFightMonsterInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SFightMonsterInfo& default_instance();

  void Swap(SFightMonsterInfo* other);

  // implements Message ----------------------------------------------

  SFightMonsterInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SFightMonsterInfo& from);
  void MergeFrom(const SFightMonsterInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 monsterId = 1;
  inline bool has_monsterid() const;
  inline void clear_monsterid();
  static const int kMonsterIdFieldNumber = 1;
  inline ::google::protobuf::int32 monsterid() const;
  inline void set_monsterid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SFightMonsterInfo)
 private:
  inline void set_has_monsterid();
  inline void clear_has_monsterid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 monsterid_;
  friend void  protobuf_AddDesc_SFightMonsterInfo_2eproto();
  friend void protobuf_AssignDesc_SFightMonsterInfo_2eproto();
  friend void protobuf_ShutdownFile_SFightMonsterInfo_2eproto();

  void InitAsDefaultInstance();
  static SFightMonsterInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// SFightMonsterInfo

// required int32 monsterId = 1;
inline bool SFightMonsterInfo::has_monsterid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SFightMonsterInfo::set_has_monsterid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SFightMonsterInfo::clear_has_monsterid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SFightMonsterInfo::clear_monsterid() {
  monsterid_ = 0;
  clear_has_monsterid();
}
inline ::google::protobuf::int32 SFightMonsterInfo::monsterid() const {
  // @@protoc_insertion_point(field_get:SFightMonsterInfo.monsterId)
  return monsterid_;
}
inline void SFightMonsterInfo::set_monsterid(::google::protobuf::int32 value) {
  set_has_monsterid();
  monsterid_ = value;
  // @@protoc_insertion_point(field_set:SFightMonsterInfo.monsterId)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SFightMonsterInfo_2eproto__INCLUDED
