// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SPvpRoomEnermyInfo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SPvpRoomEnermyInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SPvpRoomEnermyInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SPvpRoomEnermyInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_SPvpRoomEnermyInfo_2eproto() {
  protobuf_AddDesc_SPvpRoomEnermyInfo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SPvpRoomEnermyInfo.proto");
  GOOGLE_CHECK(file != NULL);
  SPvpRoomEnermyInfo_descriptor_ = file->message_type(0);
  static const int SPvpRoomEnermyInfo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SPvpRoomEnermyInfo, hair_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SPvpRoomEnermyInfo, body_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SPvpRoomEnermyInfo, weapon_),
  };
  SPvpRoomEnermyInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SPvpRoomEnermyInfo_descriptor_,
      SPvpRoomEnermyInfo::default_instance_,
      SPvpRoomEnermyInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SPvpRoomEnermyInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SPvpRoomEnermyInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SPvpRoomEnermyInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SPvpRoomEnermyInfo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SPvpRoomEnermyInfo_descriptor_, &SPvpRoomEnermyInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SPvpRoomEnermyInfo_2eproto() {
  delete SPvpRoomEnermyInfo::default_instance_;
  delete SPvpRoomEnermyInfo_reflection_;
}

void protobuf_AddDesc_SPvpRoomEnermyInfo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030SPvpRoomEnermyInfo.proto\"@\n\022SPvpRoomEn"
    "ermyInfo\022\014\n\004hair\030\001 \002(\005\022\014\n\004body\030\002 \002(\005\022\016\n\006"
    "weapon\030\003 \002(\005B9\n\"com.thanple.gs.common.ni"
    "o.protocolB\023_SPvpRoomEnermyInfo", 151);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SPvpRoomEnermyInfo.proto", &protobuf_RegisterTypes);
  SPvpRoomEnermyInfo::default_instance_ = new SPvpRoomEnermyInfo();
  SPvpRoomEnermyInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SPvpRoomEnermyInfo_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SPvpRoomEnermyInfo_2eproto {
  StaticDescriptorInitializer_SPvpRoomEnermyInfo_2eproto() {
    protobuf_AddDesc_SPvpRoomEnermyInfo_2eproto();
  }
} static_descriptor_initializer_SPvpRoomEnermyInfo_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int SPvpRoomEnermyInfo::kHairFieldNumber;
const int SPvpRoomEnermyInfo::kBodyFieldNumber;
const int SPvpRoomEnermyInfo::kWeaponFieldNumber;
#endif  // !_MSC_VER

SPvpRoomEnermyInfo::SPvpRoomEnermyInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SPvpRoomEnermyInfo)
}

void SPvpRoomEnermyInfo::InitAsDefaultInstance() {
}

SPvpRoomEnermyInfo::SPvpRoomEnermyInfo(const SPvpRoomEnermyInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SPvpRoomEnermyInfo)
}

void SPvpRoomEnermyInfo::SharedCtor() {
  _cached_size_ = 0;
  hair_ = 0;
  body_ = 0;
  weapon_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SPvpRoomEnermyInfo::~SPvpRoomEnermyInfo() {
  // @@protoc_insertion_point(destructor:SPvpRoomEnermyInfo)
  SharedDtor();
}

void SPvpRoomEnermyInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SPvpRoomEnermyInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SPvpRoomEnermyInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SPvpRoomEnermyInfo_descriptor_;
}

const SPvpRoomEnermyInfo& SPvpRoomEnermyInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SPvpRoomEnermyInfo_2eproto();
  return *default_instance_;
}

SPvpRoomEnermyInfo* SPvpRoomEnermyInfo::default_instance_ = NULL;

SPvpRoomEnermyInfo* SPvpRoomEnermyInfo::New() const {
  return new SPvpRoomEnermyInfo;
}

void SPvpRoomEnermyInfo::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<SPvpRoomEnermyInfo*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(hair_, weapon_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SPvpRoomEnermyInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SPvpRoomEnermyInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 hair = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &hair_)));
          set_has_hair();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_body;
        break;
      }

      // required int32 body = 2;
      case 2: {
        if (tag == 16) {
         parse_body:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &body_)));
          set_has_body();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_weapon;
        break;
      }

      // required int32 weapon = 3;
      case 3: {
        if (tag == 24) {
         parse_weapon:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &weapon_)));
          set_has_weapon();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SPvpRoomEnermyInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SPvpRoomEnermyInfo)
  return false;
#undef DO_
}

void SPvpRoomEnermyInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SPvpRoomEnermyInfo)
  // required int32 hair = 1;
  if (has_hair()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->hair(), output);
  }

  // required int32 body = 2;
  if (has_body()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->body(), output);
  }

  // required int32 weapon = 3;
  if (has_weapon()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->weapon(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:SPvpRoomEnermyInfo)
}

::google::protobuf::uint8* SPvpRoomEnermyInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SPvpRoomEnermyInfo)
  // required int32 hair = 1;
  if (has_hair()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->hair(), target);
  }

  // required int32 body = 2;
  if (has_body()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->body(), target);
  }

  // required int32 weapon = 3;
  if (has_weapon()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->weapon(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SPvpRoomEnermyInfo)
  return target;
}

int SPvpRoomEnermyInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 hair = 1;
    if (has_hair()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->hair());
    }

    // required int32 body = 2;
    if (has_body()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->body());
    }

    // required int32 weapon = 3;
    if (has_weapon()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->weapon());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SPvpRoomEnermyInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SPvpRoomEnermyInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SPvpRoomEnermyInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SPvpRoomEnermyInfo::MergeFrom(const SPvpRoomEnermyInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_hair()) {
      set_hair(from.hair());
    }
    if (from.has_body()) {
      set_body(from.body());
    }
    if (from.has_weapon()) {
      set_weapon(from.weapon());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SPvpRoomEnermyInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SPvpRoomEnermyInfo::CopyFrom(const SPvpRoomEnermyInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SPvpRoomEnermyInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void SPvpRoomEnermyInfo::Swap(SPvpRoomEnermyInfo* other) {
  if (other != this) {
    std::swap(hair_, other->hair_);
    std::swap(body_, other->body_);
    std::swap(weapon_, other->weapon_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SPvpRoomEnermyInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SPvpRoomEnermyInfo_descriptor_;
  metadata.reflection = SPvpRoomEnermyInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
