// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SRequestPvpRooms.proto

#ifndef PROTOBUF_SRequestPvpRooms_2eproto__INCLUDED
#define PROTOBUF_SRequestPvpRooms_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_SRequestPvpRooms_2eproto();
void protobuf_AssignDesc_SRequestPvpRooms_2eproto();
void protobuf_ShutdownFile_SRequestPvpRooms_2eproto();

class SRequestPvpRooms;
class SRequestPvpRooms_Item;

// ===================================================================

class SRequestPvpRooms_Item : public ::google::protobuf::Message {
 public:
  SRequestPvpRooms_Item();
  virtual ~SRequestPvpRooms_Item();

  SRequestPvpRooms_Item(const SRequestPvpRooms_Item& from);

  inline SRequestPvpRooms_Item& operator=(const SRequestPvpRooms_Item& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRequestPvpRooms_Item& default_instance();

  void Swap(SRequestPvpRooms_Item* other);

  // implements Message ----------------------------------------------

  SRequestPvpRooms_Item* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRequestPvpRooms_Item& from);
  void MergeFrom(const SRequestPvpRooms_Item& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 instanceId = 1;
  inline bool has_instanceid() const;
  inline void clear_instanceid();
  static const int kInstanceIdFieldNumber = 1;
  inline ::google::protobuf::int32 instanceid() const;
  inline void set_instanceid(::google::protobuf::int32 value);

  // required int32 status = 2;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 2;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SRequestPvpRooms.Item)
 private:
  inline void set_has_instanceid();
  inline void clear_has_instanceid();
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 instanceid_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_SRequestPvpRooms_2eproto();
  friend void protobuf_AssignDesc_SRequestPvpRooms_2eproto();
  friend void protobuf_ShutdownFile_SRequestPvpRooms_2eproto();

  void InitAsDefaultInstance();
  static SRequestPvpRooms_Item* default_instance_;
};
// -------------------------------------------------------------------

class SRequestPvpRooms : public ::google::protobuf::Message {
 public:
  SRequestPvpRooms();
  virtual ~SRequestPvpRooms();

  SRequestPvpRooms(const SRequestPvpRooms& from);

  inline SRequestPvpRooms& operator=(const SRequestPvpRooms& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SRequestPvpRooms& default_instance();

  void Swap(SRequestPvpRooms* other);

  // implements Message ----------------------------------------------

  SRequestPvpRooms* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRequestPvpRooms& from);
  void MergeFrom(const SRequestPvpRooms& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef SRequestPvpRooms_Item Item;

  // accessors -------------------------------------------------------

  // repeated .SRequestPvpRooms.Item rooms = 1;
  inline int rooms_size() const;
  inline void clear_rooms();
  static const int kRoomsFieldNumber = 1;
  inline const ::SRequestPvpRooms_Item& rooms(int index) const;
  inline ::SRequestPvpRooms_Item* mutable_rooms(int index);
  inline ::SRequestPvpRooms_Item* add_rooms();
  inline const ::google::protobuf::RepeatedPtrField< ::SRequestPvpRooms_Item >&
      rooms() const;
  inline ::google::protobuf::RepeatedPtrField< ::SRequestPvpRooms_Item >*
      mutable_rooms();

  // @@protoc_insertion_point(class_scope:SRequestPvpRooms)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::SRequestPvpRooms_Item > rooms_;
  friend void  protobuf_AddDesc_SRequestPvpRooms_2eproto();
  friend void protobuf_AssignDesc_SRequestPvpRooms_2eproto();
  friend void protobuf_ShutdownFile_SRequestPvpRooms_2eproto();

  void InitAsDefaultInstance();
  static SRequestPvpRooms* default_instance_;
};
// ===================================================================


// ===================================================================

// SRequestPvpRooms_Item

// required int32 instanceId = 1;
inline bool SRequestPvpRooms_Item::has_instanceid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRequestPvpRooms_Item::set_has_instanceid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRequestPvpRooms_Item::clear_has_instanceid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRequestPvpRooms_Item::clear_instanceid() {
  instanceid_ = 0;
  clear_has_instanceid();
}
inline ::google::protobuf::int32 SRequestPvpRooms_Item::instanceid() const {
  // @@protoc_insertion_point(field_get:SRequestPvpRooms.Item.instanceId)
  return instanceid_;
}
inline void SRequestPvpRooms_Item::set_instanceid(::google::protobuf::int32 value) {
  set_has_instanceid();
  instanceid_ = value;
  // @@protoc_insertion_point(field_set:SRequestPvpRooms.Item.instanceId)
}

// required int32 status = 2;
inline bool SRequestPvpRooms_Item::has_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SRequestPvpRooms_Item::set_has_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SRequestPvpRooms_Item::clear_has_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SRequestPvpRooms_Item::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 SRequestPvpRooms_Item::status() const {
  // @@protoc_insertion_point(field_get:SRequestPvpRooms.Item.status)
  return status_;
}
inline void SRequestPvpRooms_Item::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:SRequestPvpRooms.Item.status)
}

// -------------------------------------------------------------------

// SRequestPvpRooms

// repeated .SRequestPvpRooms.Item rooms = 1;
inline int SRequestPvpRooms::rooms_size() const {
  return rooms_.size();
}
inline void SRequestPvpRooms::clear_rooms() {
  rooms_.Clear();
}
inline const ::SRequestPvpRooms_Item& SRequestPvpRooms::rooms(int index) const {
  // @@protoc_insertion_point(field_get:SRequestPvpRooms.rooms)
  return rooms_.Get(index);
}
inline ::SRequestPvpRooms_Item* SRequestPvpRooms::mutable_rooms(int index) {
  // @@protoc_insertion_point(field_mutable:SRequestPvpRooms.rooms)
  return rooms_.Mutable(index);
}
inline ::SRequestPvpRooms_Item* SRequestPvpRooms::add_rooms() {
  // @@protoc_insertion_point(field_add:SRequestPvpRooms.rooms)
  return rooms_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SRequestPvpRooms_Item >&
SRequestPvpRooms::rooms() const {
  // @@protoc_insertion_point(field_list:SRequestPvpRooms.rooms)
  return rooms_;
}
inline ::google::protobuf::RepeatedPtrField< ::SRequestPvpRooms_Item >*
SRequestPvpRooms::mutable_rooms() {
  // @@protoc_insertion_point(field_mutable_list:SRequestPvpRooms.rooms)
  return &rooms_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SRequestPvpRooms_2eproto__INCLUDED
