// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SRequestTaskStatus.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SRequestTaskStatus.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SRequestTaskStatus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SRequestTaskStatus_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* SRequestTaskStatus_Status_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_SRequestTaskStatus_2eproto() {
  protobuf_AddDesc_SRequestTaskStatus_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SRequestTaskStatus.proto");
  GOOGLE_CHECK(file != NULL);
  SRequestTaskStatus_descriptor_ = file->message_type(0);
  static const int SRequestTaskStatus_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SRequestTaskStatus, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SRequestTaskStatus, status_),
  };
  SRequestTaskStatus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SRequestTaskStatus_descriptor_,
      SRequestTaskStatus::default_instance_,
      SRequestTaskStatus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SRequestTaskStatus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SRequestTaskStatus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SRequestTaskStatus));
  SRequestTaskStatus_Status_descriptor_ = SRequestTaskStatus_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SRequestTaskStatus_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SRequestTaskStatus_descriptor_, &SRequestTaskStatus::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SRequestTaskStatus_2eproto() {
  delete SRequestTaskStatus::default_instance_;
  delete SRequestTaskStatus_reflection_;
}

void protobuf_AddDesc_SRequestTaskStatus_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030SRequestTaskStatus.proto\"\200\001\n\022SRequestT"
    "askStatus\022\014\n\004type\030\001 \002(\005\022*\n\006status\030\002 \002(\0162"
    "\032.SRequestTaskStatus.Status\"0\n\006Status\022\r\n"
    "\tNOT_START\020\000\022\013\n\007OPENING\020\001\022\n\n\006FINISH\020\002B9\n"
    "\"com.thanple.gs.common.nio.protocolB\023_SR"
    "equestTaskStatus", 216);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SRequestTaskStatus.proto", &protobuf_RegisterTypes);
  SRequestTaskStatus::default_instance_ = new SRequestTaskStatus();
  SRequestTaskStatus::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SRequestTaskStatus_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SRequestTaskStatus_2eproto {
  StaticDescriptorInitializer_SRequestTaskStatus_2eproto() {
    protobuf_AddDesc_SRequestTaskStatus_2eproto();
  }
} static_descriptor_initializer_SRequestTaskStatus_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* SRequestTaskStatus_Status_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SRequestTaskStatus_Status_descriptor_;
}
bool SRequestTaskStatus_Status_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const SRequestTaskStatus_Status SRequestTaskStatus::NOT_START;
const SRequestTaskStatus_Status SRequestTaskStatus::OPENING;
const SRequestTaskStatus_Status SRequestTaskStatus::FINISH;
const SRequestTaskStatus_Status SRequestTaskStatus::Status_MIN;
const SRequestTaskStatus_Status SRequestTaskStatus::Status_MAX;
const int SRequestTaskStatus::Status_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int SRequestTaskStatus::kTypeFieldNumber;
const int SRequestTaskStatus::kStatusFieldNumber;
#endif  // !_MSC_VER

SRequestTaskStatus::SRequestTaskStatus()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SRequestTaskStatus)
}

void SRequestTaskStatus::InitAsDefaultInstance() {
}

SRequestTaskStatus::SRequestTaskStatus(const SRequestTaskStatus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SRequestTaskStatus)
}

void SRequestTaskStatus::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0;
  status_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SRequestTaskStatus::~SRequestTaskStatus() {
  // @@protoc_insertion_point(destructor:SRequestTaskStatus)
  SharedDtor();
}

void SRequestTaskStatus::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SRequestTaskStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SRequestTaskStatus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SRequestTaskStatus_descriptor_;
}

const SRequestTaskStatus& SRequestTaskStatus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SRequestTaskStatus_2eproto();
  return *default_instance_;
}

SRequestTaskStatus* SRequestTaskStatus::default_instance_ = NULL;

SRequestTaskStatus* SRequestTaskStatus::New() const {
  return new SRequestTaskStatus;
}

void SRequestTaskStatus::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<SRequestTaskStatus*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(type_, status_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SRequestTaskStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SRequestTaskStatus)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 type = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_status;
        break;
      }

      // required .SRequestTaskStatus.Status status = 2;
      case 2: {
        if (tag == 16) {
         parse_status:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::SRequestTaskStatus_Status_IsValid(value)) {
            set_status(static_cast< ::SRequestTaskStatus_Status >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SRequestTaskStatus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SRequestTaskStatus)
  return false;
#undef DO_
}

void SRequestTaskStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SRequestTaskStatus)
  // required int32 type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  // required .SRequestTaskStatus.Status status = 2;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->status(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:SRequestTaskStatus)
}

::google::protobuf::uint8* SRequestTaskStatus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SRequestTaskStatus)
  // required int32 type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  // required .SRequestTaskStatus.Status status = 2;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->status(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SRequestTaskStatus)
  return target;
}

int SRequestTaskStatus::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

    // required .SRequestTaskStatus.Status status = 2;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SRequestTaskStatus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SRequestTaskStatus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SRequestTaskStatus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SRequestTaskStatus::MergeFrom(const SRequestTaskStatus& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_status()) {
      set_status(from.status());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SRequestTaskStatus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SRequestTaskStatus::CopyFrom(const SRequestTaskStatus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SRequestTaskStatus::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void SRequestTaskStatus::Swap(SRequestTaskStatus* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(status_, other->status_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SRequestTaskStatus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SRequestTaskStatus_descriptor_;
  metadata.reflection = SRequestTaskStatus_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
