// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SRequestTaskStatus.proto

package com.thanple.gs.common.nio.protocol;

public final class _SRequestTaskStatus {
  private _SRequestTaskStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SRequestTaskStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SRequestTaskStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>required .SRequestTaskStatus.Status status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .SRequestTaskStatus.Status status = 2;</code>
     */
    com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status getStatus();
  }
  /**
   * Protobuf type {@code SRequestTaskStatus}
   */
  public static final class SRequestTaskStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SRequestTaskStatus)
      SRequestTaskStatusOrBuilder {
    // Use SRequestTaskStatus.newBuilder() to construct.
    private SRequestTaskStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SRequestTaskStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SRequestTaskStatus defaultInstance;
    public static SRequestTaskStatus getDefaultInstance() {
      return defaultInstance;
    }

    public SRequestTaskStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SRequestTaskStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status value = com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanple.gs.common.nio.protocol._SRequestTaskStatus.internal_static_SRequestTaskStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanple.gs.common.nio.protocol._SRequestTaskStatus.internal_static_SRequestTaskStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.class, com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<SRequestTaskStatus> PARSER =
        new com.google.protobuf.AbstractParser<SRequestTaskStatus>() {
      public SRequestTaskStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SRequestTaskStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SRequestTaskStatus> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code SRequestTaskStatus.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NOT_START = 0;</code>
       */
      NOT_START(0, 0),
      /**
       * <code>OPENING = 1;</code>
       */
      OPENING(1, 1),
      /**
       * <code>FINISH = 2;</code>
       */
      FINISH(2, 2),
      ;

      /**
       * <code>NOT_START = 0;</code>
       */
      public static final int NOT_START_VALUE = 0;
      /**
       * <code>OPENING = 1;</code>
       */
      public static final int OPENING_VALUE = 1;
      /**
       * <code>FINISH = 2;</code>
       */
      public static final int FINISH_VALUE = 2;


      public final int getNumber() { return value; }

      public static Status valueOf(int value) {
        switch (value) {
          case 0: return NOT_START;
          case 1: return OPENING;
          case 2: return FINISH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Status(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SRequestTaskStatus.Status)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status status_;
    /**
     * <code>required .SRequestTaskStatus.Status status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .SRequestTaskStatus.Status status = 2;</code>
     */
    public com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status getStatus() {
      return status_;
    }

    private void initFields() {
      type_ = 0;
      status_ = com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status.NOT_START;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SRequestTaskStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SRequestTaskStatus)
        com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thanple.gs.common.nio.protocol._SRequestTaskStatus.internal_static_SRequestTaskStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thanple.gs.common.nio.protocol._SRequestTaskStatus.internal_static_SRequestTaskStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.class, com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Builder.class);
      }

      // Construct using com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status.NOT_START;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thanple.gs.common.nio.protocol._SRequestTaskStatus.internal_static_SRequestTaskStatus_descriptor;
      }

      public com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus getDefaultInstanceForType() {
        return com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.getDefaultInstance();
      }

      public com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus build() {
        com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus buildPartial() {
        com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus result = new com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus) {
          return mergeFrom((com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus other) {
        if (other == com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status status_ = com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status.NOT_START;
      /**
       * <code>required .SRequestTaskStatus.Status status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .SRequestTaskStatus.Status status = 2;</code>
       */
      public com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status getStatus() {
        return status_;
      }
      /**
       * <code>required .SRequestTaskStatus.Status status = 2;</code>
       */
      public Builder setStatus(com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .SRequestTaskStatus.Status status = 2;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.thanple.gs.common.nio.protocol._SRequestTaskStatus.SRequestTaskStatus.Status.NOT_START;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SRequestTaskStatus)
    }

    static {
      defaultInstance = new SRequestTaskStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SRequestTaskStatus)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SRequestTaskStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SRequestTaskStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030SRequestTaskStatus.proto\"\200\001\n\022SRequestT" +
      "askStatus\022\014\n\004type\030\001 \002(\005\022*\n\006status\030\002 \002(\0162" +
      "\032.SRequestTaskStatus.Status\"0\n\006Status\022\r\n" +
      "\tNOT_START\020\000\022\013\n\007OPENING\020\001\022\n\n\006FINISH\020\002B9\n" +
      "\"com.thanple.gs.common.nio.protocolB\023_SR" +
      "equestTaskStatus"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SRequestTaskStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SRequestTaskStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SRequestTaskStatus_descriptor,
        new java.lang.String[] { "Type", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
